"""Initial PostGIS graph models

Revision ID: af739ff5cace
Revises: 
Create Date: 2026-03-29 22:56:40.297818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'af739ff5cace'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, nullable=False), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)

    op.create_table('edges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_node_id', sa.Integer(), nullable=False),
        sa.Column('end_node_id', sa.Integer(), nullable=False),
        sa.Column('base_weight', sa.Float(), nullable=False),
        sa.Column('current_risk_weight', sa.Float(), nullable=False),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, nullable=False), nullable=False),
        sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
        sa.ForeignKeyConstraint(['end_node_id'], ['nodes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)

    op.create_table('risk_zones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('intensity', sa.Float(), nullable=False),
        sa.Column('radius', sa.Float(), nullable=False),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, nullable=False), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_zones_id'), 'risk_zones', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_zones_id'), table_name='risk_zones')
    op.drop_table('risk_zones')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
